### PR TITLE
Support Ruby 3.2 and 3.3

### PR DESCRIPTION
**Pull request by christopher-b**
Adding support for Ruby versions 3.2 and 3.3 :metal:

### CODE REVIEW

**Comment by christopher-b** [comment]
Resolves #17

**Review by reynoldsalec — DISMISSED** [review]
This looks great @christopher-b! Only comment would be to add a CHANGELOG.md entry ;)

**Review by uberhacker — CHANGES_REQUESTED** [review]
Update CHANGELOG.md?

**Comment by christopher-b** [comment]
> This looks great @christopher-b! Only comment would be to add a CHANGELOG.md entry ;)

Done. Indicated as release v1.2.0

**Review by reynoldsalec — APPROVED** [review]

**Review by uberhacker — APPROVED** [review]

**Comment by reynoldsalec** [comment]
...you even made the CHANGELOG entry past-tense @christopher-b, I'm sure there's a little tear of joy in @pirog's eye right now.

**Pull request merged**
